### ISSUE TITLE
Why p(duration_time) and y(start_index_input) have to times 100?

### ISSUE THREAD

**Issue by shipleyxie** [rijuldhir/Qbe_encoded_model#2]
Hi @rijuldhir i come across this problem ,Could you please give me some guide?
```
if float(p)*100 > 120:
            continue    # continue jump out of this loop , break will jump out of all loop
if float(y)+float(p) > 14:
            continue
        #print(_,y,p)
readUtt(_,float(y)*100,float(p)*100)
step_num = int(float(p)*100)
```

**Comment by rijuldhir** [comment]
First if for trimming the size of the word till 120 frames (e.g making max size -120).
You might not need the second if as I just used it because size more than 14 gave me out of memory error on my PC.

**Comment by rijuldhir** [comment]
The data I had was 100 frames per sec so if a data is 1.24 sec it means it has 124 frames
